log_level: 1

plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    #- name: 'MiOSsiri'
    ##git: 'git://github.com/Hackworth/SPVoice-MiOS.git'
      #path: 'PATH'
      #mios_host: 'IP_ADDRESS'

    #- name: 'XBMC'
      #path: 'PATH'
      #xbmc_host: 'IP_ADDRESS' #Internal IP address of your computer running XBMC.
      #xbmc_port: 8081          #Port that the XBMC interface listens to.      
      #xbmc_username: 'xbmc'    #Username as specified in XBMC
      #xbmc_password: ''    #password as specified in XBMC
